export enum ResponseMessage {
  SuccessfulRegistration = 'Registration successful',
  SuccessfulLogin = 'Login successful',
  LogoutSuccessful = 'Logged out successfully',
  UpdateUser = 'User updated successfully',
  UserProfile = 'User profile',
  QuestionCreation = 'Question created successfully',
  ListQuestions = 'List of questions',
  DeleteQuestion = 'Question deleted successfully',
  GetTag = 'Tag',
  UpdateTag = 'Tag updated successfully',
  CreateAnswer = 'Answer created successfully',
  UpdateAnswer = 'Answer updated successfully',
  GetAnswer = 'List of answers to this question',
  DeleteAnswer = 'Answer deleted successfully',
  Search = 'Searched result',
  ZeroSearch = 'No result found',
  Vote = 'Vote created',
  EnableOrDisableTwoFa = 'Two factor authentication is enabled or disabled',
  SendTwoFaToken = 'Token sent successfully',
  VerifyTwoFa = 'Two Factor Authenticaton Verification successful',
  SubscribeToQuestion = 'Subscription to question is successful',
  UnsubscribeQuestion = 'Successfully unsubscribe to question',
  CountQuestions = 'Question counted'
}
